version: 2

updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"

  - package-ecosystem: "docker"
    directory: "/cuda-gpu"
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: "*"

  - package-ecosystem: "docker"
    directory: "/backend"
    schedule:
      interval: "monthly"

  - package-ecosystem: "docker"
    directory: "/infrastructure"
    schedule:
      interval: "monthly"
